/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.motorph.ui.swing;

import com.motorph.domain.models.UserAccount;
import com.motorph.repository.csv.CsvUserAccountRepository;
import com.motorph.service.AccessControlService;
import com.motorph.service.AuthService;
import javax.swing.*;

/**
 * The Main Window of the application.
 * It acts as a container that swaps between the Login Panel and Dashboard Panel.
 * @author ACER
 */
public class MainFrame extends JFrame {
    
    // Services needed by the panels
    private AuthService authService;

    public MainFrame() {
        // 1. Initialize Services (Dependency Injection)
        // We create them here and pass them down to the panels
        this.authService = new AuthService(new CsvUserAccountRepository());

        // 2. Setup the Main Window
        setTitle("MotorPH Payroll System");
        setSize(800, 600); // Default size
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); // Center on screen
        
        // 3. Start with the Login Screen
        showLoginPanel();
    }

    /**
     * Switches the current view to the Login Panel.
     */
    public void showLoginPanel() {
        // Create the Login Panel and pass the AuthService to it
        LoginView loginPanel = new LoginView(authService);
        
        // Clear old content and add the new panel
        setContentPane(loginPanel);
        revalidate();
        repaint();
    }

    /**
     * Switches the current view to the Main Dashboard.
     * Called by LoginView when login is successful.
     * @param user The logged-in user.
     */
public void showDashboard(UserAccount user) {
        // Create the Access Control Service
        AccessControlService accessService = new AccessControlService();

        // --- DECISION TREE ---
        
        if (accessService.checkAccess(user, "ItDashboardView")) {
             // JOptionPane.showMessageDialog(this, "Opening IT Dashboard...");
             // setContentPane(new ItDashboardView()); 
             System.out.println("Opening IT Dashboard");
             
        } else if (accessService.checkAccess(user, "ManagerDashboardView")) {
             // setContentPane(new ManagerDashboardView(user));
             System.out.println("Opening Manager Dashboard");

        } else if (accessService.checkAccess(user, "PayrollDashboardView")) {
             // setContentPane(new PayrollDashboardView());
             System.out.println("Opening Payroll Dashboard");

        } else {
             // Default for everyone else (Regular Employees)
             // setContentPane(new EmployeePortalView(user));
             System.out.println("Opening Employee Portal");
        }

        revalidate();
        repaint();
    }

    // --- APPLICATION ENTRY POINT ---
    public static void main(String[] args) {
        // Use SwingUtilities to ensure thread safety
        SwingUtilities.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
